# Generated by Django 4.2.17 on 2025-01-20 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='employees',
            table='employees',
        ),
    ]
